"""test

Revision ID: 0e47837cd3f0
Revises: d212f48c9d44
Create Date: 2025-03-27 16:19:53.485780

"""

from typing import Sequence, Union

from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "0e47837cd3f0"
down_revision: Union[str, None] = "d212f48c9d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
