"""test

Revision ID: d212f48c9d44
Revises: 3cacfcbf2b06
Create Date: 2025-03-27 14:45:44.715211

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d212f48c9d44"
down_revision: Union[str, None] = "3cacfcbf2b06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
